#pragma once

/*
    Copyright(C) 2023 Tyler Crockett | Macdaddy4sure.com

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissionsand
    limitations under the License.
*/

#include "AugmentedIntelligence.hpp"

using namespace std;

class _Algebra
{
public:

    class Terms
    {
    public:
        static string AbsoluteValue(string text);
        static string Algebra(string text);
        static string AlgebraGrid(string text);
        static string ArithmeticSequence(string text);
        static string AssociativeLawOfAddition(string text);
        static string AssociativeLawOfMultiplication(string text);
        static string AxisOfSymmetry(string text);
        static string Base(string text);
        static string BestFitLine(string text);
        static string BoxPlot(string text);
        static string BreakEven(string text);
        static string CeilingFunction(string text);
        static string ClearingDenominators(string text);
        static string Coefficient(string text);
        static string CombineLikeTerms(string text);
        static string CommonDifference(string text);
        static string CommonRatio(string text);
        static string CommunitiveLawOfAddition(string text);
        static string CommunitiveLawOfMultiplication(string text);
        static string CompletingTheSquare(string text);
        static string Composition(string text);
        static string ConditionalRelativeFrequency(string text);
        static string Constant(string text);
        static string ConstantCoefficient(string text);
        static string ConstantTerm(string text);
        static string Coordinates(string text);
        static string CoordinatePlane(string text);
        static string CoordinateGrid(string text);
        static string CorrelationCoefficient(string text);
        static string Cost(string text);
        static string CubeRoot(string text);
        static string Data(string text);
        static string Decimal(string text);
        static string Denominator(string text);
        static string Difference(string text);
        static string Dialation(string text);
        static string Discriminant(string text);
        static string DistributiveLawOfMultiplicationOverAddition(string text);
        static string DistributiveLawOfMultiplicationOverSubtraction(string text);
        static string Domain(string text);
        static string DotPlot(string text);
        static string Equation(string text);
        static string Equivalent(string text);
        static string EvenFunction(string text);
        static string ExpandingAnExpression(string text);
        static string Exponent(string text);
        static string Exponential(string text);
        static string ExponentialDecay(string text);
        static string ExponentialGrowth(string text);
        static string Expression(string text);
        static string Factor(string text);
        static string Factoring(string text);
        static string FibonacciSequence(string text);
        static string FirstQuartile(string text);
        static string FloorFunction(string text);
        static string Formula(string text);
        static string Fraction(string text);
        static string Frequency(string text);
        static string Function(string text);
        static string FundamentalTheoremOfArithmetic(string text);
        static string GeometricSequence(string text);
        static string Graph(string text);
        static string Histogram(string text);
        static string Horizontal(string text);
        static string ImproperFraction(string text);
        static string Inequality(string text);
        static string Infinite(string text);
        static string Input(string text);
        static string Integer(string text);
        static string InterquartileRange(string text);
        static string InverseFunctions(string text);
        static string IrrationalNumber(string text);
        static string Isolate(string text);
        static string JointFrequency(string text);
        static string JointRelativeFrequency(string text);
        static string LawsOfExponents(string text);
        static string Linear(string text);
        static string LinearCoefficient(string text);
        static string LinearModel(string text);
        static string LinearOptimization(string text);
        static string MarginalFrequency(string text);
        static string MarginalRelativeFrequency(string text);
        static string Mean(string text);
        static string MeanAbsoluteDeviation(string text);
        static string MeanSquaredDeviation(string text);
        static string Median(string text);
        static string Mode(string text);
        static string Monic(string text);
        static string Monomial(string text);
        static string Negate(string text);
        static string NegativeNumber(string text);
        static string NthRoot(string text);
        static string Numerator(string text);
        static string OddFunction(string text);
        static string OneToOne(string text);
        static string Origin(string text);
        static string Outlier(string text);
        static string Output(string text);
        static string Parabola(string text);
        static string Parallel(string text);
        static string PerfectSquare(string text);
        static string Period(string text);
        static string PeriodicFunction(string text);
        static string Perpendicular(string text);
        static string PiecewiseDefinedFunction(string text);
        static string Point(string text);
        static string PointOfSymmetry(string text);
        static string PointSlopeForm(string text);
        static string Polynomial(string text);
        static string PositiveNumber(string text);
        static string Power(string text);
        static string PrimeNumber(string text);
        static string Product(string text);
        static string Profit(string text);
        static string Quadrant(string text);
        static string Quadratic(string text);
        static string QuadraticCoefficient(string text);
        static string Quartiles(string text);
        static string Quotient(string text);
        static string Range(string text);
        static string RateOfChange(string text);
        static string RationalNumber(string text);
        static string Reflection(string text);
        static string Relation(string text);
        static string RelativeFrequency(string text);
        static string Residual(string text);
        static string Restriction(string text);
        static string Revenue(string text);
        static string RigidMotion(string text);
        static string RootMeanSquareError(string text);
        static string Roots(string text);
        static string Rotation(string text);
        static string ScatterPlot(string text);
        static string Sequence(string text);
        static string Set(string text);
        static string Similar(string text);
        static string Simplify(string text);
        static string Slope(string text);
        static string SlopeInterceptForm(string text);
        static string Solution(string text);
        static string SolutionSet(string text);
        static string Solve(string text);
        static string SquareRoot(string text);
        static string StandardDeviation(string text);
        static string StandardForm(string text);
        static string Statistic(string text);
        static string Statistics(string text);
        static string StepFunction(string text);
        static string Substitution(string text);
        static string Sum(string text);
        static string Symmetry(string text);
        static string System(string text);
        static string Table(string text);
        static string Term(string text);
        static string QuadraticFormula(string text);
        static string ThirdQuartile(string text);
        static string Translation(string text);
        static string TwoWayFrequencyTable(string text);
        static string Unit(string text);
        static string Value(string text);
        static string Variable(string text);
        static string Variance(string text);
        static string Vertex(string text);
        static string VertexForm(string text);
        static string Vertical(string text);
        static string WholeNumber(string text);
        static string XAxis(string text);
        static string XCoordinate(string text);
        static string XIntercept(string text);
        static string YAxis(string text);
        static string YCoordinate(string text);
        static string YIntercept(string text);
        static string Zeros(string text);
    };

    class Definitions
    {
    public:
        static string AbsoluteValue();
        static string Algebra();
        static string AlgebraGrid();
        static string ArithmeticSequence();
        static string AssociativeLawOfAddition();
        static string AssociativeLawOfMultiplication();
        static string AxisOfSymmetry();
        static string Base();
        static string BestFitLine();
        static string BoxPlot();
        static string BreakEven();
        static string CeilingFunction();
        static string ClearingDenominators();
        static string Coefficient();
        static string CombineLikeTerms();
        static string CommonDifference();
        static string CommonRatio();
        static string CommunitiveLawOfAddition();
        static string CommunitiveLawOfMultiplication();
        static string CompletingTheSquare();
        static string Composition();
        static string ConditionalRelativeFrequency();
        static string Constant();
        static string ConstantCoefficient();
        static string ConstantTerm();
        static string Coordinates();
        static string CoordinatePlane();
        static string CoordinateGrid();
        static string CorrelationCoefficient();
        static string Cost();
        static string CubeRoot();
        static string Data();
        static string Decimal();
        static string Denominator();
        static string Difference();
        static string Dialation();
        static string Discriminant();
        static string DistributiveLawOfMultiplicationOverAddition();
        static string DistributiveLawOfMultiplicationOverSubtraction();
        static string Domain();
        static string DotPlot();
        static string Equation();
        static string Equivalent();
        static string EvenFunction();
        static string ExpandingAnExpression();
        static string Exponent();
        static string Exponential();
        static string ExponentialDecay();
        static string ExponentialGrowth();
        static string Expression();
        static string Factor();
        static string Factoring();
        static string FibonacciSequence();
        static string FirstQuartile();
        static string FloorFunction();
        static string Formula();
        static string Fraction();
        static string Frequency();
        static string Function();
        static string FundamentalTheoremOfArithmetic();
        static string GeometricSequence();
        static string Graph();
        static string Histogram();
        static string Horizontal();
        static string ImproperFraction();
        static string Inequality();
        static string Infinite();
        static string Input();
        static string Integer();
        static string InterquartileRange();
        static string InverseFunctions();
        static string IrrationalNumber();
        static string Isolate();
        static string JointFrequency();
        static string JointRelativeFrequency();
        static string LawsOfExponents();
        static string Linear();
        static string LinearCoefficient();
        static string LinearModel();
        static string LinearOptimization();
        static string MarginalFrequency();
        static string MarginalRelativeFrequency();
        static string Mean();
        static string MeanAbsoluteDeviation();
        static string MeanSquaredDeviation();
        static string Median();
        static string Mode();
        static string Monic();
        static string Monomial();
        static string Negate();
        static string NegativeNumber();
        static string NthRoot();
        static string Numerator();
        static string OddFunction();
        static string OneToOne();
        static string Origin();
        static string Outlier();
        static string Output();
        static string Parabola();
        static string Parallel();
        static string PerfectSquare();
        static string Period();
        static string PeriodicFunction();
        static string Perpendicular();
        static string PiecewiseDefinedFunction();
        static string Point();
        static string PointOfSymmetry();
        static string PointSlopeForm();
        static string Polynomial();
        static string PositiveNumber();
        static string Power();
        static string PrimeNumber();
        static string Product();
        static string Profit();
        static string Quadrant();
        static string Quadratic();
        static string QuadraticCoefficient();
        static string Quartiles();
        static string Quotient();
        static string Range();
        static string RateOfChange();
        static string RationalNumber();
        static string Reflection();
        static string Relation();
        static string RelativeFrequency();
        static string Residual();
        static string Restriction();
        static string Revenue();
        static string RigidMotion();
        static string RootMeanSquareError();
        static string Roots();
        static string Rotation();
        static string ScatterPlot();
        static string Sequence();
        static string Set();
        static string Similar();
        static string Simplify();
        static string Slope();
        static string SlopeInterceptForm();
        static string Solution();
        static string SolutionSet();
        static string Solve();
        static string SquareRoot();
        static string StandardDeviation();
        static string StandardForm();
        static string Statistic();
        static string Statistics();
        static string StepFunction();
        static string Substitution();
        static string Sum();
        static string Symmetry();
        static string System();
        static string Table();
        static string Term();
        static string QuadraticFormula();
        static string ThirdQuartile();
        static string Translation();
        static string TwoWayFrequencyTable();
        static string Unit();
        static string Value();
        static string Variable();
        static string Variance();
        static string Vertex();
        static string VertexForm();
        static string Vertical();
        static string WholeNumber();
        static string XAxis();
        static string XCoordinate();
        static string XIntercept();
        static string YAxis();
        static string YCoordinate();
        static string YIntercept();
        static string Zeros();
    };

    class Vision
    {
    public:
        static string AbsoluteValue(string image_location);
        static string Algebra(string image_location);
        static string AlgebraGrid(string image_location);
        static string ArithmeticSequence(string image_location);
        static string AssociativeLawOfAddition(string image_location);
        static string AssociativeLawOfMultiplication(string image_location);
        static string AxisOfSymmetry(string image_location);
        static string Base(string image_location);
        static string BestFitLine(string image_location);
        static string BoxPlot(string image_location);
        static string BreakEven(string image_location);
        static string CeilingFunction(string image_location);
        static string ClearingDenominators(string image_location);
        static string Coefficient(string image_location);
        static string CombineLikeTerms(string image_location);
        static string CommonDifference(string image_location);
        static string CommonRatio(string image_location);
        static string CommunitiveLawOfAddition(string image_location);
        static string CommunitiveLawOfMultiplication(string image_location);
        static string CompletingTheSquare(string image_location);
        static string Composition(string image_location);
        static string ConditionalRelativeFrequency(string image_location);
        static string Constant(string image_location);
        static string ConstantCoefficient(string image_location);
        static string ConstantTerm(string image_location);
        static string Coordinates(string image_location);
        static string CoordinatePlane(string image_location);
        static string CoordinateGrid(string image_location);
        static string CorrelationCoefficient(string image_location);
        static string Cost(string image_location);
        static string CubeRoot(string image_location);
        static string Data(string image_location);
        static string Decimal(string image_location);
        static string Denominator(string image_location);
        static string Difference(string image_location);
        static string Dialation(string image_location);
        static string Discriminant(string image_location);
        static string DistributiveLawOfMultiplicationOverAddition(string image_location);
        static string DistributiveLawOfMultiplicationOverSubtraction(string image_location);
        static string Domain(string image_location);
        static string DotPlot(string image_location);
        static string Equation(string image_location);
        static string Equivalent(string image_location);
        static string EvenFunction(string image_location);
        static string ExpandingAnExpression(string image_location);
        static string Exponent(string image_location);
        static string Exponential(string image_location);
        static string ExponentialDecay(string image_location);
        static string ExponentialGrowth(string image_location);
        static string Expression(string image_location);
        static string Factor(string image_location);
        static string Factoring(string image_location);
        static string FibonacciSequence(string image_location);
        static string FirstQuartile(string image_location);
        static string FloorFunction(string image_location);
        static string Formula(string image_location);
        static string Fraction(string image_location);
        static string Frequency(string image_location);
        static string Function(string image_location);
        static string FundamentalTheoremOfArithmetic(string image_location);
        static string GeometricSequence(string image_location);
        static string Graph(string image_location);
        static string Histogram(string image_location);
        static string Horizontal(string image_location);
        static string ImproperFraction(string image_location);
        static string Inequality(string image_location);
        static string Infinite(string image_location);
        static string Input(string image_location);
        static string Integer(string image_location);
        static string InterquartileRange(string image_location);
        static string InverseFunctions(string image_location);
        static string IrrationalNumber(string image_location);
        static string Isolate(string image_location);
        static string JointFrequency(string image_location);
        static string JointRelativeFrequency(string image_location);
        static string LawsOfExponents(string image_location);
        static string Linear(string image_location);
        static string LinearCoefficient(string image_location);
        static string LinearModel(string image_location);
        static string LinearOptimization(string image_location);
        static string MarginalFrequency(string image_location);
        static string MarginalRelativeFrequency(string image_location);
        static string Mean(string image_location);
        static string MeanAbsoluteDeviation(string image_location);
        static string MeanSquaredDeviation(string image_location);
        static string Median(string image_location);
        static string Mode(string image_location);
        static string Monic(string image_location);
        static string Monomial(string image_location);
        static string Negate(string image_location);
        static string NegativeNumber(string image_location);
        static string NthRoot(string image_location);
        static string Numerator(string image_location);
        static string OddFunction(string image_location);
        static string OneToOne(string image_location);
        static string Origin(string image_location);
        static string Outlier(string image_location);
        static string Output(string image_location);
        static string Parabola(string image_location);
        static string Parallel(string image_location);
        static string PerfectSquare(string image_location);
        static string Period(string image_location);
        static string PeriodicFunction(string image_location);
        static string Perpendicular(string image_location);
        static string PiecewiseDefinedFunction(string image_location);
        static string Point(string image_location);
        static string PointOfSymmetry(string image_location);
        static string PointSlopeForm(string image_location);
        static string Polynomial(string image_location);
        static string PositiveNumber(string image_location);
        static string Power(string image_location);
        static string PrimeNumber(string image_location);
        static string Product(string image_location);
        static string Profit(string image_location);
        static string Quadrant(string image_location);
        static string Quadratic(string image_location);
        static string QuadraticCoefficient(string image_location);
        static string Quartiles(string image_location);
        static string Quotient(string image_location);
        static string Range(string image_location);
        static string RateOfChange(string image_location);
        static string RationalNumber(string image_location);
        static string Reflection(string image_location);
        static string Relation(string image_location);
        static string RelativeFrequency(string image_location);
        static string Residual(string image_location);
        static string Restriction(string image_location);
        static string Revenue(string image_location);
        static string RigidMotion(string image_location);
        static string RootMeanSquareError(string image_location);
        static string Roots(string image_location);
        static string Rotation(string image_location);
        static string ScatterPlot(string image_location);
        static string Sequence(string image_location);
        static string Set(string image_location);
        static string Similar(string image_location);
        static string Simplify(string image_location);
        static string Slope(string image_location);
        static string SlopeInterceptForm(string image_location);
        static string Solution(string image_location);
        static string SolutionSet(string image_location);
        static string Solve(string image_location);
        static string SquareRoot(string image_location);
        static string StandardDeviation(string image_location);
        static string StandardForm(string image_location);
        static string Statistic(string image_location);
        static string Statistics(string image_location);
        static string StepFunction(string image_location);
        static string Substitution(string image_location);
        static string Sum(string image_location);
        static string Symmetry(string image_location);
        static string System(string image_location);
        static string Table(string image_location);
        static string Term(string image_location);
        static string QuadraticFormula(string image_location);
        static string ThirdQuartile(string image_location);
        static string Translation(string image_location);
        static string TwoWayFrequencyTable(string image_location);
        static string Unit(string image_location);
        static string Value(string image_location);
        static string Variable(string image_location);
        static string Variance(string image_location);
        static string Vertex(string image_location);
        static string VertexForm(string image_location);
        static string Vertical(string image_location);
        static string WholeNumber(string image_location);
        static string XAxis(string image_location);
        static string XCoordinate(string image_location);
        static string XIntercept(string image_location);
        static string YAxis(string image_location);
        static string YCoordinate(string image_location);
        static string YIntercept(string image_location);
        static string Zeros(string image_location);
    };
};