#pragma once

/*
    Copyright(C) 2024 Tyler Crockett | Macdaddy4sure.com

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissionsand
    limitations under the License.
*/

#include "AugmentedIntelligence.hpp"

using namespace std;

class _ArtificialIntelligence
{
public:

    class Terms
    {
    public:
        static string AStarSearch(string text);
        static string AbductiveLogicProgramming(string text);
        static string AbductiveReasoning(string text);
        static string Ablatin(string text);
        static string AbstractDataType(string text);
        static string Abstraction(string text);
        static string AcceleratingChange(string text);
        static string ActionLanguage(string text);
        static string ActionModelLearning(string text);
        static string ActionSelection(string text);
        static string ActivationFunction(string text);
        static string AdaptiveAlgorithm(string text);
        static string AdmissibleHeuristic(string text);
        static string AffectiveComputing(string text);
        static string AgentArchitecture(string text);
        static string AIAccelerator(string text);
        static string AIComplete(string text);
        static string Algorithm(string text);
        static string AlgorithmicEfficiency(string text);
        static string AlgorithmicProbability(string text);
        static string AlphaGO(string text);
        static string AmbientIntelligence(string text);
        static string AnalysisOfAlgorithms(string text);
        //static string AnalysisOfAlgorithms(string text);
        static string Analytics(string text);
        static string AnswerSetProgrammnig(string text);
        static string AntColonyOptimization(string text);
        static string AnytimeAlgorithm(string text);
        static string ApplicationProgrammingInterface(string text);
        static string ApproximateStringMatching(string text);
        static string ApproximationError(string text);
        static string ArgumentationFramework(string text);
        static string ArtificialGeneralIntelligence(string text);
        static string ArtificialImmuneSystem(string text);
        static string ArtificialIntelligence(string text);
        static string ArtificialIntelligenceMarkupLanguage(string text);
        static string AssociationForTheAdvancementOfArtificialIntelligence(string text);
        static string AsymptoticComputationalComplexity(string text);
        static string AttentionMechanism(string text);
        static string AttributionalCalculus(string text);
        static string AugmentedReality(string text);
        static string Autoencoder(string text);
        static string AutomataTheory(string text);
        static string AutomatedMachineLearning(string text);
        static string AutomatedPlanningAndScheduling(string text);
        static string AutomatedReasoning(string text);
        static string AutonomicComputing(string text);
        static string AutonomousCar(string text);
        static string AutonomousRobot(string text);
        static string Backpropagation(string text);
        static string BackpropagationThroughStructure(string text);
        static string BackpropagationThroughTime(string text);
        static string BagOfWordsModel(string text);
        static string BagOfWordsModelInComputerVision(string text);
        static string BatchNormalization(string text);
        static string BayesianProgramming(string text);
        static string BeesAlgorithm(string text);
        static string BehaviorInformatics(string text);
        static string BehaviorTree(string text);
        static string BeliefDesireIntentionSoftwareModel(string text);
        static string BiasVarianceTradeoff(string text);
        static string BigData(string text);
        static string BigONotation(string text);
        static string BinaryTree(string text);
        static string BlackboardSystem(string text);
        static string BoltzmannMachine(string text);
        static string BooleanSatisfiabilityProblem(string text);
        static string Boosting(string text);
        static string BootstrapAggregating(string text);
        static string BrainTechnology(string text);
        static string BranchingFactor(string text);
        static string BruteForceSearch(string text);
        static string CapsuleNeuralNetwork(string text);
        static string CaseBasedReasoning(string text);
        static string ChatBot(string text);
        static string CloudRobotics(string text);
        static string ClusterAnalysis(string text);
        static string Cobweb(string text);
        static string CognativeArchitecture(string text);
        static string CognitiveComputing(string text);
        static string CognitiveScience(string text);
        static string CombinatorialOptimization(string text);
        static string CommitteeMachine(string text);
        static string CommonsenseKnowledge(string text);
        static string CommonsenseReasoning(string text);
        static string ComputationalChemistry(string text);
        static string ComputationalComplexityTheory(string text);
        static string ComputationalCreativity(string text);
        static string ComputationalCybernetics(string text);
        static string ComputationalHumor(string text);
        static string ComputationalIntelligence(string text);
        static string ComputationalLearningTheory(string text);
        static string ComputationalLinguistics(string text);
        static string ComputationalMathematics(string text);
        static string ComputationalNeuroscience(string text);
        static string ComputationalNumberTheory(string text);
        static string ComputationalProblem(string text);
        static string ComputationalStatistics(string text);
        static string ComputerAutomatedDesign(string text);
        //static string ComputerAutomatedDesign(string text);
        static string ComputerAudition(string text);
        static string ComputerScience(string text);
        static string ComputerVision(string text);
        static string ConceptDrift(string text);
        static string Connectionism(string text);
        static string ConsistentHeuristic(string text);
        static string ConstrainedConditionalModel(string text);
        static string ConstraintLogicProgramming(string text);
        static string ConstraintProgramming(string text);
        static string ConstructedLanguage(string text);
        static string ControlTheory(string text);
        static string ConvolutionalNeuralNetwork(string text);
        static string Crossover(string text);
        static string DarkForest(string text);
        static string DartmouthWorkshop(string text);
        static string DataAugmentation(string text);
        static string DataFusion(string text);
        static string DataMining(string text);
        static string DataScience(string text);
        static string DataSet(string text);
        static string DataWarehouse(string text);
        static string Datalog(string text);
        static string DecisionBoundry(string text);
        static string DecisionSupportSystem(string text);
        static string DecisionTheory(string text);
        static string DecisionTreeLearning(string text);
        static string DeductiveClassifier(string text);
        //static string DecisionTreeLearning(string text);
        static string DeclarativeProgramming(string text);
        //static string DeductiveClassifier(string text);
        static string DeepBlue(string text);
        static string DeepLearning(string text);
        static string DeemMindTechnologies(string text);
        static string DefaultLogic(string text);
        static string DensityBasedSpatialClusteringOfApplicationsWithNoise(string text);
        static string DescriptionLogic(string text);
        static string DevelopmentalRobotics(string text);
        static string Diagnosis(string text);
        static string DialogueSystem(string text);
        static string DiffusionModel(string text);
        static string DijkstrasAlgorithm(string text);
        static string DimensionalityReduction(string text);
        static string DiscreteSystem(string text);
        static string DistributedArtificialIntelligence(string text);
        static string DoubleDescent(string text);
        static string Dropout(string text);
        static string DynamicEpistemicLogic(string text);
        static string EagerLearning(string text);
        static string EarlyStopping(string text);
        static string EbertTest(string text);
        static string EchoStateNetwork(string text);
        static string EmbodiedAgent(string text);
        static string EmbodiedCognitiveScience(string text);
        static string ErrorDrivenLearning(string text);
        //static string ErrorDrivenLearning(string text);
        static string EnsembleLearning(string text);
        static string Epoch(string text);
        static string EthicsOfArtificialIntelligence(string text);
        static string EvolutionaryAlgorithm(string text);
        static string EvolutionaryComputation(string text);
        static string EvolvingClassificationFunction(string text);
        static string ExistentialRisk(string text);
        static string ExpertSystem(string text);
        static string FastAndFrugalTrees(string text);
        static string Feature(string text);
        static string FeatureExtraction(string text);
        static string FeatureLearning(string text);
        static string FeatureSelection(string text);
        static string FederatedLearning(string text);
        static string FirstOrderLogic(string text);
        static string Fluent(string text);
        static string FormalLanguage(string text);
        static string ForwardChaining(string text);
        static string Frame(string text);
        static string FrameLanguage(string text);
        static string FrameProblem(string text);
        static string FriendlyArtificialIntelligence(string text);
        static string FuturesStudies(string text);
        static string FuzzyControlSystem(string text);
        static string FuzzyLogic(string text);
        static string FuzzyRule(string text);
        static string FuzzySet(string text);
        static string GameTheory(string text);
        static string GeneralGamePlaying(string text);
        static string Generalization(string text);
        static string GeneralizationError(string text);
        static string GenerativeAdversarialNetwork(string text);
        static string GenerativeArtificialIntelligence(string text);
        static string GenerativePretrainedTransformer(string text);
        static string GeneticAlgorithm(string text);
        static string GeneticOperator(string text);
        static string GlowwormSwarmOptimization(string text);
        static string GradientBoosting(string text);
        static string GraphAbstractDataType(string text);
        static string GraphDiscreteMathematics(string text);
        static string GraphDatabase(string text);
        static string GraphTheory(string text);
        static string GraphTransversal(string text);
        static string Hallucination(string text);
        static string Heuristic(string text);
        static string HiddenLayer(string text);
        static string HyperHeuristic(string text);
        static string Hyperperameter(string text);
        static string HyperperameterOptimization(string text);
        static string Hyperplane(string text);
        static string IEEEComputationalIntelligenceSociety(string text);
        static string IncrementalLearning(string text);
        static string InferenceEngine(string text);
        static string InformationIntegration(string text);
        static string InformationProcessingLanguage(string text);
        static string IntelligenceAmplification(string text);
        static string IntelligenceExplosion(string text);
        static string IntelligentAgent(string text);
        static string IntelligentControl(string text);
        static string IntelligentPersonalAssistant(string text);
        static string Interpretation(string text);
        static string IntrinsicMotivation(string text);
        static string IssueTree(string text);
        static string JunctionTreeAlgorithm(string text);
        static string KernelMethod(string text);
        static string KLONE(string text);
        static string KNearestNeighbors(string text);
        static string KnowledgeAcquisition(string text);
        static string KnowledgeBasedSystem(string text);
        static string KnowledgeDistilation(string text);
        static string KnowledgeEngineering(string text);
        static string KnowledgeExtraction(string text);
        static string KnowledgeInterchangeFormat(string text);
        static string KnowledgeRepresentationAndReasoning(string text);
        static string KMeansClustering(string text);
        static string LanguageModel(string text);
        static string LargeLanguageModel(string text);
        static string LazyLearning(string text);
        static string LISP(string text);
        static string LogicProgramming(string text);
        static string LongShortTermMemory(string text);
        static string MachineVision(string text);
        static string MarkovChain(string text);
        static string MarkovDecisionProcess(string text);
        static string MathematicalOptimization(string text);
        static string MachineLearning(string text);
        static string MachineListening(string text);
        static string MachinePerception(string text);
        static string MechanismDesign(string text);
        //static string Mechatronics(string text);
        static string MetabolicNetworkReconstructionAndSimulation(string text);
        static string Metaheuristic(string text);
        static string ModelChecking(string text);
        static string ModusTollens(string text);
        static string MonteCarloTreeSearch(string text);
        static string MultiAgentSystem(string text);
        static string MultilayerPerceptron(string text);
        static string MultiSwarmOptimization(string text);
        static string Mutation(string text);
        static string Mycin(string text);
        static string NaiveBayesClassifier(string text);
        static string NaiveSemantics(string text);
        static string NameBinding(string text);
        static string NamedEntityRecognition(string text);
        static string NamedGraph(string text);
        static string NaturalLanguageGeneration(string text);
        static string NaturalLanguageProcessing(string text);
        static string NaturalLangugeProgramming(string text);
        static string NetworkMotif(string text);
        static string NeuralMachineTranslation(string text);
        static string NeuralNetwork(string text);
        static string NeuralTuringMachine(string text);
        static string NeuroFuzzy(string text);
        static string Neurocybernetic(string text);
        static string NeuromorphicEngineering(string text);
        static string Node(string text);
        static string NondeterministicAlgorithm(string text);
        static string NouvelleAI(string text);
        static string NP(string text);
        static string NPCompleteness(string text);
        static string NPHardness(string text);
        static string OccamsRazor(string text);
        static string OfflineLearnnig(string text);
        static string OnlineMachineLearning(string text);
        static string OntologicalLearning(string text);
        static string OpenAI(string text);
        static string OpenCog(string text);
        static string OpenMindCommonSense(string text);
        static string OpenSourceSoftware(string text);
        static string Overfitting(string text);
        static string PartialOrderReduction(string text);
        static string PartiallyObservableMarkovDecisionProcess(string text);
        static string ParticalSwarmOptimization(string text);
        static string Pathfinding(string text);
        static string PatternRecognition(string text);
        static string Perceptron(string text);
        static string PredicateLogic(string text);
        static string PredictiveAnalytics(string text);
        static string PrincipalComponentAnalysis(string text);
        static string PrincipleOfRationality(string text);
        static string ProbabalisticProgramming(string text);
        static string ProductionSystem(string text);
        static string ProgrammingLanguage(string text);
        static string Prolog(string text);
        static string PropositionalCalculus(string text);
        static string ProximalPolicyOptimization(string text);
        static string Python(string text);
        static string PyTorch(string text);
        static string QLearning(string text);
        static string QualificationProblem(string text);
        static string Quantifier(string text);
        static string QuantumComputing(string text);
        static string QueryLanguage(string text);
        static string RProgrammingLanguage(string text);
        static string RadialBasisFunctionNetwork(string text);
        static string RandomForest(string text);
        static string ReasoningSystem(string text);
        static string RecurrentNeuralNetwork(string text);
        static string RegressionAnalysis(string text);
        static string Regularization(string text);
        static string ReinforcementLearning(string text);
        static string ReinforcementLearningFromHumanFeedback(string text);
        static string RepresentationLearning(string text);
        static string ReservoirComputing(string text);
        static string ResourceDescriptionFramework(string text);
        static string RestrictedBoltzmannMachine(string text);
        static string ReteAlgorithm(string text);
        static string Robotics(string text);
        static string RuleBasedSystem(string text);
        static string Satisfiability(string text);
        static string SearchAlgorithm(string text);
        static string Selection(string text);
        static string SelfManagement(string text);
        static string SemanticNetwork(string text);
        static string SemanticReasoner(string text);
        static string SemanticQuery(string text);
        static string Semantics(string text);
        static string SemiSupervisedLearning(string text);
        static string SensorFusion(string text);
        static string SeparationLogic(string text);
        static string SimilarityLearning(string text);
        static string SimulatedAnnealing(string text);
        static string SituatedApproach(string text);
        static string SituationalCalculus(string text);
        static string SelectiveLinearDefiniteClauseResolution(string text);
        static string Software(string text);
        static string SoftwareEngineering(string text);
        static string SpatialTemporalReasoning(string text);
        static string SPARQL(string text);
        static string SparseDictionaryLearning(string text);
        static string SpeechRecognition(string text);
        static string SpikingNeuralNetowrk(string text);
        static string State(string text);
        static string StatisticalClassification(string text);
        static string StateActionRewardStateAction(string text);
        static string StatisticalRelationalLearning(string text);
        static string StochasticOptimization(string text);
        static string StochasticSemanticAnalysis(string text);
        static string StanfordReasearchInstituteProblemSolver(string text);
        static string SubjectMatterExpert(string text);
        static string Superintelligence(string text);
        static string SupervisedLearning(string text);
        static string SuppotVectorMachines(string text);
        static string SwarmIntelligence(string text);
        static string SymbolicArtificialIntelligence(string text);
        static string SyntheticIntelligence(string text);
        static string SystemsNeuroscience(string text);
        static string TechnologicalSingularity(string text);
        static string TemporalDifferenceLearning(string text);
        static string TensorNetworkTheory(string text);
        static string Tensorflow(string text);
        static string TheoreticalComputerScience(string text);
        static string TheoryOfComputation(string text);
        static string ThompsonSampling(string text);
        static string TimeComplexity(string text);
        static string TransferLearning(string text);
        static string Transformer(string text);
        static string Transhumanism(string text);
        static string TransitionSystem(string text);
        static string TreeTraversal(string text);
        static string TrueQuantifiedBooleanFormula(string text);
        static string TuringMachine(string text);
        static string TuringTest(string text);
        static string TypeSystem(string text);
        static string UnsupervisedLearning(string text);
        static string VisionProcessingUnit(string text);
        static string ValueAlignmentComplete(string text);
        static string WeakAI(string text);
        static string WeakSupervision(string text);
        static string WordEmbedding(string text);
        static string XGBoost(string text);
        static string BackwardChaining(string text);
        //static string MarkovChain(string text);
        static string ModusPonens(string text);
        static string Watson(string text);
        static string DataIntegration(string text);
        static string AdaptiveNeuroFuzzyInferenceSystem(string text);
    };

    class Definitions
    {
    public:
        static string AStarSearch();
        static string AbductiveLogicProgramming();
        static string AbductiveReasoning();
        static string Ablatin();
        static string AbstractDataType();
        static string Abstraction();
        static string AcceleratingChange();
        static string ActionLanguage();
        static string ActionModelLearning();
        static string ActionSelection();
        static string ActivationFunction();
        static string AdaptiveAlgorithm();
        static string AdmissibleHeuristic();
        static string AffectiveComputing();
        static string AgentArchitecture();
        static string AIAccelerator();
        static string AIComplete();
        static string Algorithm();
        static string AlgorithmicEfficiency();
        static string AlgorithmicProbability();
        static string AlphaGO();
        static string AmbientIntelligence();
        static string AnalysisOfAlgorithms();
        //static string AnalysisOfAlgorithms();
        static string Analytics();
        static string AnswerSetProgrammnig();
        static string AntColonyOptimization();
        static string AnytimeAlgorithm();
        static string ApplicationProgrammingInterface();
        static string ApproximateStringMatching();
        static string ApproximationError();
        static string ArgumentationFramework();
        static string ArtificialGeneralIntelligence();
        static string ArtificialImmuneSystem();
        static string ArtificialIntelligence();
        static string ArtificialIntelligenceMarkupLanguage();
        static string AssociationForTheAdvancementOfArtificialIntelligence();
        static string AsymptoticComputationalComplexity();
        static string AttentionMechanism();
        static string AttributionalCalculus();
        static string AugmentedReality();
        static string Autoencoder();
        static string AutomataTheory();
        static string AutomatedMachineLearning();
        static string AutomatedPlanningAndScheduling();
        static string AutomatedReasoning();
        static string AutonomicComputing();
        static string AutonomousCar();
        static string AutonomousRobot();
        static string Backpropagation();
        static string BackpropagationThroughStructure();
        static string BackpropagationThroughTime();
        static string BagOfWordsModel();
        static string BagOfWordsModelInComputerVision();
        static string BatchNormalization();
        static string BayesianProgramming();
        static string BeesAlgorithm();
        static string BehaviorInformatics();
        static string BehaviorTree();
        static string BeliefDesireIntentionSoftwareModel();
        static string BiasVarianceTradeoff();
        static string BigData();
        static string BigONotation();
        static string BinaryTree();
        static string BlackboardSystem();
        static string BoltzmannMachine();
        static string BooleanSatisfiabilityProblem();
        static string Boosting();
        static string BootstrapAggregating();
        static string BrainTechnology();
        static string BranchingFactor();
        static string BruteForceSearch();
        static string CapsuleNeuralNetwork();
        static string CaseBasedReasoning();
        static string ChatBot();
        static string CloudRobotics();
        static string ClusterAnalysis();
        static string Cobweb();
        static string CognativeArchitecture();
        static string CognitiveComputing();
        static string CognitiveScience();
        static string CombinatorialOptimization();
        static string CommitteeMachine();
        static string CommonsenseKnowledge();
        static string CommonsenseReasoning();
        static string ComputationalChemistry();
        static string ComputationalComplexityTheory();
        static string ComputationalCreativity();
        static string ComputationalCybernetics();
        static string ComputationalHumor();
        static string ComputationalIntelligence();
        static string ComputationalLearningTheory();
        static string ComputationalLinguistics();
        static string ComputationalMathematics();
        static string ComputationalNeuroscience();
        static string ComputationalNumberTheory();
        static string ComputationalProblem();
        static string ComputationalStatistics();
        static string ComputerAutomatedDesign();
        //static string ComputerAutomatedDesign();
        static string ComputerAudition();
        static string ComputerScience();
        static string ComputerVision();
        static string ConceptDrift();
        static string Connectionism();
        static string ConsistentHeuristic();
        static string ConstrainedConditionalModel();
        static string ConstraintLogicProgramming();
        static string ConstraintProgramming();
        static string ConstructedLanguage();
        static string ControlTheory();
        static string ConvolutionalNeuralNetwork();
        static string Crossover();
        static string DarkForest();
        static string DartmouthWorkshop();
        static string DataAugmentation();
        static string DataFusion();
        static string DataMining();
        static string DataScience();
        static string DataSet();
        static string DataWarehouse();
        static string Datalog();
        static string DecisionBoundry();
        static string DecisionSupportSystem();
        static string DecisionTheory();
        static string DecisionTreeLearning();
        static string DeductiveClassifier();
        //static string DecisionTreeLearning();
        static string DeclarativeProgramming();
        //static string DeductiveClassifier();
        static string DeepBlue();
        static string DeepLearning();
        static string DeemMindTechnologies();
        static string DefaultLogic();
        static string DensityBasedSpatialClusteringOfApplicationsWithNoise();
        static string DescriptionLogic();
        static string DevelopmentalRobotics();
        static string Diagnosis();
        static string DialogueSystem();
        static string DiffusionModel();
        static string DijkstrasAlgorithm();
        static string DimensionalityReduction();
        static string DiscreteSystem();
        static string DistributedArtificialIntelligence();
        static string DoubleDescent();
        static string Dropout();
        static string DynamicEpistemicLogic();
        static string EagerLearning();
        static string EarlyStopping();
        static string EbertTest();
        static string EchoStateNetwork();
        static string EmbodiedAgent();
        static string EmbodiedCognitiveScience();
        static string ErrorDrivenLearning();
        //static string ErrorDrivenLearning();
        static string EnsembleLearning();
        static string Epoch();
        static string EthicsOfArtificialIntelligence();
        static string EvolutionaryAlgorithm();
        static string EvolutionaryComputation();
        static string EvolvingClassificationFunction();
        static string ExistentialRisk();
        static string ExpertSystem();
        static string FastAndFrugalTrees();
        static string Feature();
        static string FeatureExtraction();
        static string FeatureLearning();
        static string FeatureSelection();
        static string FederatedLearning();
        static string FirstOrderLogic();
        static string Fluent();
        static string FormalLanguage();
        static string ForwardChaining();
        static string Frame();
        static string FrameLanguage();
        static string FrameProblem();
        static string FriendlyArtificialIntelligence();
        static string FuturesStudies();
        static string FuzzyControlSystem();
        static string FuzzyLogic();
        static string FuzzyRule();
        static string FuzzySet();
        static string GameTheory();
        static string GeneralGamePlaying();
        static string Generalization();
        static string GeneralizationError();
        static string GenerativeAdversarialNetwork();
        static string GenerativeArtificialIntelligence();
        static string GenerativePretrainedTransformer();
        static string GeneticAlgorithm();
        static string GeneticOperator();
        static string GlowwormSwarmOptimization();
        static string GradientBoosting();
        static string GraphAbstractDataType();
        static string GraphDiscreteMathematics();
        static string GraphDatabase();
        static string GraphTheory();
        static string GraphTransversal();
        static string Hallucination();
        static string Heuristic();
        static string HiddenLayer();
        static string HyperHeuristic();
        static string Hyperperameter();
        static string HyperperameterOptimization();
        static string Hyperplane();
        static string IEEEComputationalIntelligenceSociety();
        static string IncrementalLearning();
        static string InferenceEngine();
        static string InformationIntegration();
        static string InformationProcessingLanguage();
        static string IntelligenceAmplification();
        static string IntelligenceExplosion();
        static string IntelligentAgent();
        static string IntelligentControl();
        static string IntelligentPersonalAssistant();
        static string Interpretation();
        static string IntrinsicMotivation();
        static string IssueTree();
        static string JunctionTreeAlgorithm();
        static string KernelMethod();
        static string KLONE();
        static string KNearestNeighbors();
        static string KnowledgeAcquisition();
        static string KnowledgeBasedSystem();
        static string KnowledgeDistilation();
        static string KnowledgeEngineering();
        static string KnowledgeExtraction();
        static string KnowledgeInterchangeFormat();
        static string KnowledgeRepresentationAndReasoning();
        static string KMeansClustering();
        static string LanguageModel();
        static string LargeLanguageModel();
        static string LazyLearning();
        static string LISP();
        static string LogicProgramming();
        static string LongShortTermMemory();
        static string MachineVision();
        static string MarkovChain();
        static string MarkovDecisionProcess();
        static string MathematicalOptimization();
        static string MachineLearning();
        static string MachineListening();
        static string MachinePerception();
        static string MechanismDesign();
        //static string Mechatronics();
        static string MetabolicNetworkReconstructionAndSimulation();
        static string Metaheuristic();
        static string ModelChecking();
        static string ModusTollens();
        static string MonteCarloTreeSearch();
        static string MultiAgentSystem();
        static string MultilayerPerceptron();
        static string MultiSwarmOptimization();
        static string Mutation();
        static string Mycin();
        static string NaiveBayesClassifier();
        static string NaiveSemantics();
        static string NameBinding();
        static string NamedEntityRecognition();
        static string NamedGraph();
        static string NaturalLanguageGeneration();
        static string NaturalLanguageProcessing();
        static string NaturalLangugeProgramming();
        static string NetworkMotif();
        static string NeuralMachineTranslation();
        static string NeuralNetwork();
        static string NeuralTuringMachine();
        static string NeuroFuzzy();
        static string Neurocybernetic();
        static string NeuromorphicEngineering();
        static string Node();
        static string NondeterministicAlgorithm();
        static string NouvelleAI();
        static string NP();
        static string NPCompleteness();
        static string NPHardness();
        static string OccamsRazor();
        static string OfflineLearnnig();
        static string OnlineMachineLearning();
        static string OntologicalLearning();
        static string OpenAI();
        static string OpenCog();
        static string OpenMindCommonSense();
        static string OpenSourceSoftware();
        static string Overfitting();
        static string PartialOrderReduction();
        static string PartiallyObservableMarkovDecisionProcess();
        static string ParticalSwarmOptimization();
        static string Pathfinding();
        static string PatternRecognition();
        static string Perceptron();
        static string PredicateLogic();
        static string PredictiveAnalytics();
        static string PrincipalComponentAnalysis();
        static string PrincipleOfRationality();
        static string ProbabalisticProgramming();
        static string ProductionSystem();
        static string ProgrammingLanguage();
        static string Prolog();
        static string PropositionalCalculus();
        static string ProximalPolicyOptimization();
        static string Python();
        static string PyTorch();
        static string QLearning();
        static string QualificationProblem();
        static string Quantifier();
        static string QuantumComputing();
        static string QueryLanguage();
        static string RProgrammingLanguage();
        static string RadialBasisFunctionNetwork();
        static string RandomForest();
        static string ReasoningSystem();
        static string RecurrentNeuralNetwork();
        static string RegressionAnalysis();
        static string Regularization();
        static string ReinforcementLearning();
        static string ReinforcementLearningFromHumanFeedback();
        static string RepresentationLearning();
        static string ReservoirComputing();
        static string ResourceDescriptionFramework();
        static string RestrictedBoltzmannMachine();
        static string ReteAlgorithm();
        static string Robotics();
        static string RuleBasedSystem();
        static string Satisfiability();
        static string SearchAlgorithm();
        static string Selection();
        static string SelfManagement();
        static string SemanticNetwork();
        static string SemanticReasoner();
        static string SemanticQuery();
        static string Semantics();
        static string SemiSupervisedLearning();
        static string SensorFusion();
        static string SeparationLogic();
        static string SimilarityLearning();
        static string SimulatedAnnealing();
        static string SituatedApproach();
        static string SituationalCalculus();
        static string SelectiveLinearDefiniteClauseResolution();
        static string Software();
        static string SoftwareEngineering();
        static string SpatialTemporalReasoning();
        static string SPARQL();
        static string SparseDictionaryLearning();
        static string SpeechRecognition();
        static string SpikingNeuralNetowrk();
        static string State();
        static string StatisticalClassification();
        static string StateActionRewardStateAction();
        static string StatisticalRelationalLearning();
        static string StochasticOptimization();
        static string StochasticSemanticAnalysis();
        static string StanfordReasearchInstituteProblemSolver();
        static string SubjectMatterExpert();
        static string Superintelligence();
        static string SupervisedLearning();
        static string SuppotVectorMachines();
        static string SwarmIntelligence();
        static string SymbolicArtificialIntelligence();
        static string SyntheticIntelligence();
        static string SystemsNeuroscience();
        static string TechnologicalSingularity();
        static string TemporalDifferenceLearning();
        static string TensorNetworkTheory();
        static string Tensorflow();
        static string TheoreticalComputerScience();
        static string TheoryOfComputation();
        static string ThompsonSampling();
        static string TimeComplexity();
        static string TransferLearning();
        static string Transformer();
        static string Transhumanism();
        static string TransitionSystem();
        static string TreeTraversal();
        static string TrueQuantifiedBooleanFormula();
        static string TuringMachine();
        static string TuringTest();
        static string TypeSystem();
        static string UnsupervisedLearning();
        static string VisionProcessingUnit();
        static string ValueAlignmentComplete();
        static string WeakAI();
        static string WeakSupervision();
        static string WordEmbedding();
        static string XGBoost();
        static string BackwardChaining();
        //static string MarkovChain();
        static string ModusPonens();
        static string Watson();
        static string DataIntegration();
        static string AdaptiveNeuroFuzzyInferenceSystem();
    };
};