#pragma once

/*
    Copyright(C) 2024 Tyler Crockett | Macdaddy4sure.com

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissionsand
    limitations under the License.
*/

class _Law
{
public:

    class Terms
    {
    public:
        static string Acquittal(string text);
        static string ActiveJudge(string text);
        static string AdministrativeOfficeOfTheUnitedStatesCourts(string text);
        static string Admissible(string text);
        static string AdversaryProceeding(string text);
        static string Addidavit(string text);
        static string Affirmed(string text);
        static string AlternateJuror(string text);
        static string AlternativeDisputeResolution(string text);
        static string AmicusCuriae(string text);
        static string Answer(string text);
        static string Appeal(string text);
        static string Appellant(string text);
        static string Appellate(string text);
        static string Appellee(string text);
        static string Arraignment(string text);
        static string ArticleIIIJudge(string text);
        static string Assets(string text);
        static string Assume(string text);
        static string AutomaticStay(string text);
        static string Bail(string text);
        static string Bankruptcy(string text);
        static string BankruptcyAdministrator(string text);
        static string BankruptcyCode(string text);
        static string BankruptcyCourt(string text);
        static string BankruptcyEstate(string text);
        static string BankruptcyJudge(string text);
        static string BankruptcyPetition(string text);
        static string BankruptcyTrustee(string text);
        static string BenchTrial(string text);
        static string Brief(string text);
        static string BurdenOfProof(string text);
        static string BusinessBankruptcy(string text);
        static string CapitalOffense(string text);
        static string CaseFile(string text);
        static string CaseLaw(string text);
        static string Caseload(string text);
        static string CauseOfAction(string text);
        static string Chambers(string text);
        static string Chapter11(string text);
        static string Chapter12(string text);
        static string Chapter13(string text);
        static string Chapter13Trustee(string text);
        static string Chapter15(string text);
        static string Chapter7(string text);
        static string Chapter7Trustee(string text);
        static string Chapter9(string text);
        static string ChiefJudge(string text);
        static string Claim(string text);
        static string ClassAction(string text);
        static string ClerkOfCourt(string text);
        static string Collateral(string text);
        static string CommonLaw(string text);
        static string CommunityService(string text);
        static string Complaint(string text);
        static string ConcurrentSentence(string text);
        static string Confirmation(string text);
        static string ConsecutiveSentence(string text);
        static string ConsumerBankruptcy(string text);
        static string ConsumerDebts(string text);
        static string ContingentClaim(string text);
        static string Contract(string text);
        static string Conviction(string text);
        static string Counsel(string text);
        static string Count(string text);
        static string CourtReporter(string text);
        static string CreditCounceling(string text);
        static string Creditor(string text);
        static string Damages(string text);
        static string DeFacto(string text);
        static string DeJure(string text);
        static string DeNovo(string text);
        static string DebtorsPlan(string text);
        static string DeclaratoryJudgement(string text);
        static string DefaultJudgement(string text);
        static string Defendant(string text);
        static string Deposition(string text);
        static string Discharge(string text);
        static string DischargeableDebt(string text);
        static string DisclosureStatement(string text);
        static string Discovery(string text);
        static string DismissalWithPredudice(string text);
        static string DismissalWithoutPredudice(string text);
        static string DisposableIncome(string text);
        static string Docket(string text);
        static string DueProcess(string text);
        static string EnBanc(string text);
        static string Equitable(string text);
        static string Equity(string text);
        static string Evidence(string text);
        static string ExParte(string text);
        static string ExclusionartyRule(string text);
        static string ExculpatoryEvidence(string text);
        static string ExecutoryContracts(string text);
        static string ExemptAssets(string text);
        static string ExemptionsExemptProperty(string text);
        static string FaceSheetFiling(string text);
        static string FamilyFarmer(string text);
        static string FederalPublicDefender(string text);
        static string FederalPublicDefenderOrganization(string text);
        static string FederalQuestionJurisdiction(string text);
        static string Felony(string text);
        static string File(string text);
        static string FraudulentTransfer(string text);
        static string FreshStart(string text);
        static string GrandJury(string text);
        static string HabeasCorpus(string text);
        static string Hearsay(string text);
        static string HomeConfinement(string text);
        static string Impeachment(string text);
        static string InCamera(string text);
        static string InFormaPauperis(string text);
        static string InculpatoryEvidence(string text);
        static string Indictment(string text);
        static string Information(string text);
        static string Injunction(string text);
        static string InsiderOfCorprateDebtor(string text);
        static string InsiderOfIndividualDebtor(string text);
        static string Interrogatories(string text);
        static string Issue(string text);
        static string JointAdministration(string text);
        static string JointPetition(string text);
        static string Judge(string text);
        static string Judgeship(string text);
        static string Judgement(string text);
        static string JudicialConverenceOfTheUnitedStates(string text);
        static string Jurisdiction(string text);
        static string Jurisprudence(string text);
        static string Jury(string text);
        static string JuryInstructions(string text);
        static string Lawsuit(string text);
        static string Lien(string text);
        static string LiquidatedClaim(string text);
        static string Liquidation(string text);
        static string Litigation(string text);
        static string MagistrateJudge(string text);
        static string MeansTest(string text);
        static string MentalHealthTreatment(string text);
        static string Misdemeanor(string text);
        static string Mistrial(string text);
        static string Moot(string text);
        static string Motion(string text);
        static string MotionInLimine(string text);
        static string MotionToLiftTheAutomaticStay(string text);
        static string NoAssetCase(string text);
        static string Noloontendre(string text);
        static string NondischargeableDebt(string text);
        static string NonexemptAssets(string text);
        static string ObjectionToDischargeability(string text);
        static string ObjectionToExemptions(string text);
        static string Opinion(string text);
        static string OralArgument(string text);
        static string Panel(string text);
        static string Parole(string text);
        static string PartyInInterest(string text);
        static string PerCuriam(string text);
        static string PremptoryChallenge(string text);
        static string PetitJury(string text);
        static string Petition(string text);
        static string PetitionPreparer(string text);
        static string PettyOffense(string text);
        static string Plaintiff(string text);
        static string Plan(string text);
        static string Plea(string text);
        static string Pleadings(string text);
        static string PostpetitionTransfer(string text);
        static string PrebankruptcyPlanning(string text);
        static string Precednet(string text);
        static string PerferentialDebtPayment(string text);
        static string PresentenceReport(string text);
        static string PretrialConference(string text);
        static string PretrialServices(string text);
        static string Priority(string text);
        static string PriorityClaim(string text);
        static string ProPer(string text);
        static string ProSe(string text);
        static string ProTem(string text);
        static string Probation(string text);
        static string ProbationOfficer(string text);
        static string Procedure(string text);
        static string ProofOfClaim(string text);
        static string PropertyOfTheEstate(string text);
        static string Prosecute(string text);
        static string ReaffirmationAgreement(string text);
        static string Record(string text);
        static string Redemption(string text);
        static string Remand(string text);
        static string Reverse(string text);
        static string Sanction(string text);
        static string Schedules(string text);
        static string SecuredDebt(string text);
        static string SeniorJudge(string text);
        static string Sentence(string text);
        static string SentencingGuidlines(string text);
        static string Sequester(string text);
        static string ServiceOfProcess(string text);
        static string Settlement(string text);
        static string SmallBusinessCase(string text);
        static string StandardOfProof(string text);
        static string StatementOfFinancialAffairs(string text);
        static string StatementOfIntention(string text);
        static string Statute(string text);
        static string StatuteOfLimitations(string text);
        static string SuaSponte(string text);
        static string Subordination(string text);
        static string Subpoena(string text);
        static string SupenaDucesTecum(string text);
        static string TemporaryRestrainingOrder(string text);
        static string Testimony(string text);
        static string Toll(string text);
        static string Tort(string text);
        static string Transcript(string text);
        static string Transfer(string text);
        static string Trustee(string text);
        static string TypingService(string text);
        static string USAttorney(string text);
        static string USTrustee(string text);
        static string UndersecuredClaim(string text);
        static string UndueHardship(string text);
        static string UnlawfulDetainerAction(string text);
        static string UnliquidatedClaim(string text);
        static string UnscheduledDebt(string text);
        static string UnsecuredClaim(string text);
        static string Uphold(string text);
        static string Venue(string text);
        static string Verdict(string text);
        static string Voirdire(string text);
        static string VoluntaryTransfer(string text);
        static string WageGarnishment(string text);
        static string Warrant(string text);
        static string Witness(string text);
        static string Writ(string text);
        static string WritOfCertiorari(string text);
        static string Debtor(string text);
        static string Court(string text);
        static string SecuredCreditor(string text);
    };
};